WebSpeech: fix linker error
With ENABLE_SPEECH_SYNTHESIS linking of the WPE is not possible due to the error:

undefined reference to `WebCore::PlatformSpeechSynthesizer::PlatformSpeechSynthesizer(WebCore::PlatformSpeechSynthesizerClient*)'

To fix that error a glib stub implementation of the PlatformSpeechSynthesizer is added.