Fix compiler errors with GCC-12 [GCC] with libwebrtc (USE_GSTREAMER_WEBRTC=FALSE) https://bugs.webkit.org/show_bug.cgi?id=250562
Reviewed by Philippe Normand.

With GCC version 12.2.0 the compiler stops with:
  error: control reaches end of non-void function [-Werror=return-type]
when building these files, at least since commit
9def6e6f0258ddd9171d32bec2fffb684dbc7b8b.

* Source/WebCore/Modules/mediastream/libwebrtc/LibWebRTCUtils.cpp:
(WebCore::toRTCErrorDetailType):
* Source/WebCore/testing/MockLibWebRTCPeerConnection.cpp:
(WebCore::MockLibWebRTCPeerConnection::signaling_state):

Canonical link: https://commits.webkit.org/258871@main